# $Id: Makefile.inc 2142 2008-10-08 07:26:32Z peter $

TESTS += modules/objfmts/macho/tests/gas64/gas_macho64_test.sh

EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas_macho64_test.sh
EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas-macho64.asm
EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas-macho64.hex
EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas-macho64-pic.asm
EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas-macho64-pic.hex
