#!/bin/bash

if [ -z $GCCDATE ]; then
	echo "need to set GCCDATE environment variable!"
	exit 1
fi

export BELIBRARIES=/boot/common/lib:/boot/system/develop/lib

mkdir -p binutils-obj
cd binutils-obj
CFLAGS="-O2" CXXFLAGS="-O2" ../binutils/configure \
	--prefix=/boot/common/develop/tools/gcc-2.95.3-${GCCDATE} \
	--disable-nls --enable-shared=yes
make
cd ..
